server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          username: ${GTIHUB_USER}
          password: ${GTIHUB_PASSWORD}
          default-label: main
          uri: https://github.com/xcorpiiion/micro-service-repository
          search-paths: fornecedor, loja, transportador
